server:
  port: 8888

spring:
  application:
    name: mydom-config-server
#  profiles:
#    active: dev #(native, vault)
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      server:

        vault:
          host: ${VAULT_HOST}
          port: ${VAULT_PORT}
          scheme: http
          authentication: token
          token: ${VAULT_TOKEN}        # root token gerado pelo Vault dev
          kv-version: 2
          backend: secret
          default-context: mydom-config-server # ou outro nome, como "config-common"
          profile-separator: '-'       # para buscar: secret/mydom-auth-server-default

        git:
          uri: ${GITHUB_URI}
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          default-label: main
          search-paths: config
          clone-on-start: true
          basedir: C:\myProject\mydom-solution\configurations
#        bootstrap: true

    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}  # Substitua pelo seu token real
      kv:
        enabled: true
        backend: secret
        default-context: mydom-config-server
        profile-separator: '-'

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.mariapuri.mydom.config: DEBUG