server:
  port: 8081

spring:
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_AUDIENCE}
          jwk-set-uri: ${AUTH0_DOMAIN}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
